import { createFileRoute } from "@tanstack/react-router";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Calendar } from "lucide-react";
import { mockDatasets, fairnessMetrics, recommendations } from "@/lib/mock-data";
import { toast } from "sonner";

export const Route = createFileRoute("/dashboard/reports")({
  component: Reports,
});

function Reports() {
  const generatePDF = async (datasetName: string) => {
    const { jsPDF } = await import("jspdf");
    const autoTable = (await import("jspdf-autotable")).default;
    const doc = new jsPDF();

    // Header
    doc.setFillColor(80, 100, 220);
    doc.rect(0, 0, 210, 35, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("FairMind AI", 14, 18);
    doc.setFontSize(11);
    doc.text("Fairness Audit Report", 14, 27);

    doc.setTextColor(30, 30, 60);
    doc.setFontSize(16);
    doc.text(datasetName, 14, 50);
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 140);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 57);

    // Summary
    doc.setTextColor(30, 30, 60);
    doc.setFontSize(13);
    doc.text("Executive Summary", 14, 72);
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 100);
    doc.text(`Overall Fairness Score: ${fairnessMetrics.overall}/100`, 14, 80);
    doc.text(`Compliance Status: ${fairnessMetrics.overall >= 75 ? "PASS" : "REVIEW REQUIRED"}`, 14, 86);
    doc.text(`Statistical Parity: ${fairnessMetrics.statisticalParity.toFixed(2)}`, 14, 92);
    doc.text(`Equal Opportunity: ${fairnessMetrics.equalOpportunity.toFixed(2)}`, 14, 98);
    doc.text(`Disparate Impact: ${fairnessMetrics.disparateImpact.toFixed(2)}`, 14, 104);

    // Metrics table
    autoTable(doc, {
      startY: 115,
      head: [["Group", "Selection Rate", "False Positive", "False Negative"]],
      body: fairnessMetrics.selectionRate.map((s, i) => [
        s.group,
        `${(s.rate * 100).toFixed(1)}%`,
        `${(fairnessMetrics.errorRates[i].fpr * 100).toFixed(1)}%`,
        `${(fairnessMetrics.errorRates[i].fnr * 100).toFixed(1)}%`,
      ]),
      headStyles: { fillColor: [80, 100, 220] },
    });

    // Recommendations
    autoTable(doc, {
      head: [["Priority", "Recommendation", "Impact"]],
      body: recommendations.slice(0, 5).map((r) => [r.priority.toUpperCase(), r.title, r.impact]),
      headStyles: { fillColor: [120, 180, 100] },
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 170);
    doc.text("Report generated by FairMind AI • fairmind.ai • Confidential", 14, 285);

    doc.save(`FairMind_Report_${datasetName.replace(/\s+/g, "_")}.pdf`);
    toast.success("Report downloaded!");
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Reports</h1>
        <p className="text-muted-foreground mt-1">Download professional compliance reports for any analysis.</p>
      </div>

      <div className="grid gap-4">
        {mockDatasets.map((d) => (
          <Card key={d.id} className="p-5">
            <div className="flex items-center justify-between gap-4 flex-wrap">
              <div className="flex items-center gap-4 min-w-0">
                <div className="h-12 w-12 rounded-xl bg-[image:var(--gradient-primary)] flex items-center justify-center text-primary-foreground flex-shrink-0">
                  <FileText className="h-5 w-5" />
                </div>
                <div className="min-w-0">
                  <div className="font-semibold truncate">{d.name} — Fairness Audit</div>
                  <div className="text-xs text-muted-foreground flex items-center gap-2 mt-0.5">
                    <Calendar className="h-3 w-3" /> {d.uploadedAt} • {d.rows.toLocaleString()} rows • {d.domain}
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <Badge
                  variant="secondary"
                  className={d.status === "safe" ? "bg-success/10 text-success border-0" : d.status === "warning" ? "bg-warning/10 text-warning border-0" : "bg-destructive/10 text-destructive border-0"}
                >
                  Score: {d.fairnessScore}/100
                </Badge>
                <Button onClick={() => generatePDF(d.name)} className="bg-[image:var(--gradient-primary)]">
                  <Download className="h-4 w-4 mr-2" /> Download PDF
                </Button>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}